databases:
  - name: mayday-db
    databaseName: mayday
    user: mayday
    plan: free
    region: oregon

services:
  - type: web
    name: psny-mayday
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: ./build.sh
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        fromDatabase:
          name: mayday-db
          property: connectionString
